### ISSUE TITLE
Add precommit Hook for code formatting

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/wiki#31]
**Description**
The code should be automatically formatted while a commit is made.

**Resource Reference:** [Link](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/)

**Tasks**
- [ ] Add dev dependency for [Husky and/or pretty-quick](https://prettier.io/docs/en/precommit.html#option-2-pretty-quickhttpsgithubcomazzpretty-quick)
- [ ] Add Husky and pretty-qucik in `package.json`
- [ ] Add pre-commit in `.husky`

**Comment by ritik307** [comment]
@ArunTeltia @LordShenron I would like to work on this issue plz assign.

**Comment by ArunTeltia** [comment]
Well I know what husky is but i dont think we need it because its not an enerprise level project, but for making our commit history clean we can clearly set some rules for commit message 
@LordShenron make some rules for how a commit should look like 
@ritik307 if you want to work on it go ahead, i guess this will help our project in the long run, but i am not really sure if we needed it right now 

Okay Lets Give it a shot 
Assigning this to you
